-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 30, 2022 at 08:37 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `laravel`
--

-- --------------------------------------------------------

--
-- Table structure for table `jobs`
--

CREATE TABLE `jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `queue` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempts` tinyint(3) UNSIGNED NOT NULL,
  `reserved_at` int(10) UNSIGNED DEFAULT NULL,
  `available_at` int(10) UNSIGNED NOT NULL,
  `created_at` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `jobs`
--

INSERT INTO `jobs` (`id`, `queue`, `payload`, `attempts`, `reserved_at`, `available_at`, `created_at`) VALUES
(1, 'default', '{\"uuid\":\"e1f9865a-5362-4b6f-82ad-fc4e8048dad9\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp0.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(2, 'default', '{\"uuid\":\"2e702103-2221-41ee-bd5f-0f787645504c\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp1.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(3, 'default', '{\"uuid\":\"4f311449-2efa-4d82-b2ab-52781699457c\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp10.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(4, 'default', '{\"uuid\":\"566a5c89-a512-44f1-b0f8-ee7feec135a5\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp11.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(5, 'default', '{\"uuid\":\"0dfa9398-515d-4661-b67a-29a609bd1387\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp12.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(6, 'default', '{\"uuid\":\"da68b46e-298b-421d-876f-21415cba54c8\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp13.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(7, 'default', '{\"uuid\":\"44d17823-0077-46f3-8692-072daa017c9b\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp14.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(8, 'default', '{\"uuid\":\"8f44b645-264e-4b0d-a536-60f751fc58eb\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp15.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(9, 'default', '{\"uuid\":\"dc14f136-c3b5-4af9-ad8e-bfd3ebc29f0e\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp16.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(10, 'default', '{\"uuid\":\"36f18adb-0051-48f7-9368-fbaafbec2d4a\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp17.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(11, 'default', '{\"uuid\":\"ccd60ff9-78ea-4b13-bc39-c630528a9113\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp18.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(12, 'default', '{\"uuid\":\"08cc5ccc-ab55-4d7b-80ff-ebc722eff4a9\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp19.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(13, 'default', '{\"uuid\":\"321edf2c-fa9b-4ba7-9253-478ab7985cb4\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp2.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(14, 'default', '{\"uuid\":\"b2980db2-647e-4137-84e6-a6927d84433d\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp20.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(15, 'default', '{\"uuid\":\"2f4d1039-6ffa-4845-97c6-941fe5495663\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp21.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(16, 'default', '{\"uuid\":\"e08f8b25-eac7-4770-ab24-a1c05683d716\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp22.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(17, 'default', '{\"uuid\":\"03692428-30e8-45f2-a634-332dd9413570\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp23.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(18, 'default', '{\"uuid\":\"faaa3e0d-b26a-43c4-95d5-b35f75708e7b\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp24.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(19, 'default', '{\"uuid\":\"7deaa4da-cbd9-4036-93fc-4660752beafc\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp25.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(20, 'default', '{\"uuid\":\"5bb4f065-31c1-48a5-a894-f8c74dbb0d60\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp26.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(21, 'default', '{\"uuid\":\"f21cce1f-7b7c-4f5c-9754-5890aad7b866\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp27.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(22, 'default', '{\"uuid\":\"8b8cb803-b184-4123-b9c0-65d4e27b09fa\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp28.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(23, 'default', '{\"uuid\":\"51a74c20-1111-48c3-a6fe-202fc5396b70\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp29.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(24, 'default', '{\"uuid\":\"c1fc5d50-996d-4486-9bc2-f8b6ad78a068\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp3.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(25, 'default', '{\"uuid\":\"ace245e5-1080-44d3-8392-29aa7f736689\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp30.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(26, 'default', '{\"uuid\":\"c23228a3-94d2-4fa4-80ba-b3de50859c4d\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp31.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(27, 'default', '{\"uuid\":\"f9d352e6-d247-4c87-ab66-99ddd4123015\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp32.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(28, 'default', '{\"uuid\":\"4027f59d-10d5-4903-9511-a19e869da573\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp33.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(29, 'default', '{\"uuid\":\"3ed6bba4-04aa-42aa-ba33-c9b54d661573\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp34.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(30, 'default', '{\"uuid\":\"e22cb309-fba2-45f0-a2ee-62ffdf9353d1\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp35.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(31, 'default', '{\"uuid\":\"904c7cc6-43d1-417c-a9ed-8cd0316febc1\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp36.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(32, 'default', '{\"uuid\":\"769b522d-f805-48c1-aeaf-66edadc0643e\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp37.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(33, 'default', '{\"uuid\":\"3613fc27-1f38-4357-a339-f3df4651192e\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp38.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(34, 'default', '{\"uuid\":\"d56925cd-c2b2-40ae-95b4-cd057345d7c5\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp39.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(35, 'default', '{\"uuid\":\"9ec3234b-8441-4fb5-a90f-b82889672f96\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp4.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(36, 'default', '{\"uuid\":\"df0fb7de-2850-44c6-88bf-7c322dace660\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp40.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(37, 'default', '{\"uuid\":\"4938a9af-841b-44f0-b0ae-f48c82fc78c6\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp41.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(38, 'default', '{\"uuid\":\"b109add5-2abd-4b2a-8c2b-38443aaca5a0\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp42.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(39, 'default', '{\"uuid\":\"4b8a045e-52da-4348-ba2b-98562c0ff420\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp43.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(40, 'default', '{\"uuid\":\"30224056-0c70-473c-bd3b-f5cdcd0c516a\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp44.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(41, 'default', '{\"uuid\":\"3563c3af-dcef-46da-a482-63b44ebdbad1\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp45.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(42, 'default', '{\"uuid\":\"c727b399-8a97-4116-866c-a33855eb2729\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp46.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(43, 'default', '{\"uuid\":\"f32c93f0-12f3-4e57-bf5c-a5f5cd23e4c1\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp47.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(44, 'default', '{\"uuid\":\"f0c7a0e4-921a-4be5-a7e1-7f4f84e25918\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp48.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(45, 'default', '{\"uuid\":\"d68b296e-a6e7-4e37-a173-1a07b3104f66\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp49.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(46, 'default', '{\"uuid\":\"8d37a2fd-5b6b-4b87-8d6b-9610014a35f5\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp5.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(47, 'default', '{\"uuid\":\"040b647a-e751-4b03-83b9-8af020e999e1\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp50.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(48, 'default', '{\"uuid\":\"a2ce5a8b-de86-430b-8a9c-819254271685\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp51.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(49, 'default', '{\"uuid\":\"8af2bd16-7103-4d8a-9228-ed1eecfc3819\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp52.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(50, 'default', '{\"uuid\":\"0f74f664-4f89-4053-bb04-93117ed567ba\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp53.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(51, 'default', '{\"uuid\":\"67c69045-aaf6-458f-b2d0-e7fcdb7302e9\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp54.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(52, 'default', '{\"uuid\":\"dac3a133-5a23-4883-bc95-0f76a87946c4\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp55.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(53, 'default', '{\"uuid\":\"ef9b5e2a-8192-4318-a217-d0fb891a363b\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp56.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(54, 'default', '{\"uuid\":\"a2fcef24-f133-4b85-a683-a30221e60825\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp57.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(55, 'default', '{\"uuid\":\"df9078c3-1723-43dd-beb4-7d1d9fb86875\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp58.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(56, 'default', '{\"uuid\":\"4537415d-b7af-419b-bfcb-845bd0fbf1b4\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp59.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(57, 'default', '{\"uuid\":\"6accdae9-1f24-45ab-a64b-58fc4d368454\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp6.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(58, 'default', '{\"uuid\":\"53f825dc-9b90-4654-93df-bf827f82e2dd\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp60.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(59, 'default', '{\"uuid\":\"71c50ef3-adff-48a0-9b8b-7e220672d999\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp61.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(60, 'default', '{\"uuid\":\"dec3e1b0-37a0-4483-ad47-d87ffb5d346c\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp62.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970);
INSERT INTO `jobs` (`id`, `queue`, `payload`, `attempts`, `reserved_at`, `available_at`, `created_at`) VALUES
(61, 'default', '{\"uuid\":\"59147a96-54ea-42cf-888b-0606458a1d36\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp63.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(62, 'default', '{\"uuid\":\"787b04c3-38ff-4606-935d-f88626b34947\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp64.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(63, 'default', '{\"uuid\":\"0c741a33-ef45-4f59-aeec-42ef3857ca33\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp65.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(64, 'default', '{\"uuid\":\"117c7753-c7ca-42cd-b048-5dce2b8a4ac0\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp66.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(65, 'default', '{\"uuid\":\"427fce44-7dbe-4be5-a22b-a8a2cfe55d1f\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp67.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(66, 'default', '{\"uuid\":\"e660a0df-b6fd-43b4-9b42-72149ff86716\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp68.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(67, 'default', '{\"uuid\":\"0936bbae-1d28-46e1-8522-e1e6aa5ebb2d\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp69.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(68, 'default', '{\"uuid\":\"2f349fe7-2a96-4083-b6e9-fa901804968d\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp7.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(69, 'default', '{\"uuid\":\"e4d0a237-9c50-4356-b17b-71d16c551279\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp70.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(70, 'default', '{\"uuid\":\"fc3578e3-ce48-4c3e-8de2-c06a1bf04b40\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp71.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(71, 'default', '{\"uuid\":\"a7fa25af-cc1b-4d89-a271-efabdc221099\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp72.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(72, 'default', '{\"uuid\":\"1cd59d83-4032-4199-ad21-e896241ef919\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp73.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(73, 'default', '{\"uuid\":\"70f5132e-34ed-47fc-b4f9-b05b4a0188d3\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp74.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(74, 'default', '{\"uuid\":\"cba8adfb-f38a-4cfa-bd54-46f7bc82e94e\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp75.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(75, 'default', '{\"uuid\":\"743dbc69-8364-4b43-bc2d-0d1a41231695\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp76.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(76, 'default', '{\"uuid\":\"1b493d26-d6e6-42cc-9f89-2ec1e0b3ad42\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp77.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(77, 'default', '{\"uuid\":\"5a27b4ec-75a9-4d70-bd99-ca9bba3b81de\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp78.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(78, 'default', '{\"uuid\":\"8e997663-bb71-4924-8e4a-5b396aa20c58\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp79.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(79, 'default', '{\"uuid\":\"b9e09fab-7df6-4f6d-a2de-6986c2c9f2a1\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp8.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(80, 'default', '{\"uuid\":\"87b53a8f-29f6-4e7f-ae85-dba0969e3c80\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp80.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(81, 'default', '{\"uuid\":\"d837ccd5-be40-4c01-a90e-e03fb9a48673\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp81.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(82, 'default', '{\"uuid\":\"96a7c1db-dbcb-4e5b-be13-b765649b5872\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp82.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(83, 'default', '{\"uuid\":\"72c5e273-704e-46a5-b362-96df59c42e48\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp83.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(84, 'default', '{\"uuid\":\"3cf3a320-84bd-4ba7-84b0-1e90b13d2fc3\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp84.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(85, 'default', '{\"uuid\":\"3c4f7431-c5dd-4586-a3e7-0eab2a185a32\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp85.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(86, 'default', '{\"uuid\":\"80de96b9-b4ea-4550-88f9-add8b5773d2e\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp86.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(87, 'default', '{\"uuid\":\"7c8e30b5-b660-4fcf-a959-88e6a6f5c865\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp87.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(88, 'default', '{\"uuid\":\"76b34524-abcb-4dc0-b314-0f8de8199b5f\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:58:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp88.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970),
(89, 'default', '{\"uuid\":\"6939834f-80da-44e5-aeb2-a0ddee818ef6\",\"displayName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"maxExceptions\":null,\"failOnTimeout\":false,\"backoff\":null,\"timeout\":null,\"retryUntil\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\ProcessCSVData\",\"command\":\"O:23:\\\"App\\\\Jobs\\\\ProcessCSVData\\\":11:{s:4:\\\"file\\\";s:57:\\\"D:\\\\sanjana\\\\laravel\\\\fee-assignment\\\\resources\\\\temp\\/tmp9.csv\\\";s:3:\\\"job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:19:\\\"chainCatchCallbacks\\\";N;s:5:\\\"delay\\\";N;s:11:\\\"afterCommit\\\";N;s:10:\\\"middleware\\\";a:0:{}s:7:\\\"chained\\\";a:0:{}}\"}}', 0, NULL, 1664562970, 1664562970);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `jobs`
--
ALTER TABLE `jobs`
  ADD PRIMARY KEY (`id`),
  ADD KEY `jobs_queue_index` (`queue`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `jobs`
--
ALTER TABLE `jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=90;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
